### PR TITLE
Improved Linting + Made Hamburger Menu Optional + Improved Example and README

### PR DESCRIPTION
**Pull request by aditya113141**
- Follow up to [this](https://github.com/Jamalianpour/easy_sidemenu/pull/77). Made Hamburger Icon optional
- Improved Linting 
- Updated Example with `showHamburger` and `sideMenuExpansionItem`
- Updated README with `showHamburger`

### CODE REVIEW

**Comment by Jamalianpour** [comment]
Thanks, I will review it as soon as possible

**Comment by Jamalianpour** [comment]
There is not any problem with lint, thanks

But I have some issue with `Expansion Item`:
* The title text was cut from the bottom
* If I change `showHamburger` and use hot reload the title of the item was shown in compact mode

Screenshot 2024-01-07 at 10 08 10 PM
Screenshot 2024-01-07 at 10 08 23 PM

**Comment by aditya113141** [comment]
Working on it.

**Comment by aditya113141** [comment]
@Jamalianpour Can you verify ?

**Pull request merged**
