### PR TITLE
adding the possibility to use other ways to navigate, example

### PR DESCRIPTION
**Pull request by nimr77**
like using the routing

### CODE REVIEW

**Comment by nimr77** [comment]
also Linux support for the example

**Comment by Jamalianpour** [comment]
Hello,
I run example on MacOS and web, but it will freezes when tried to change pages.

**Comment by nimr77** [comment]
the example is freezing !? 
it works on my changes, is it the same example, can you provide a snapshot of it if it's not

I have tested it on Linux and the web

**Comment by nimr77** [comment]
here is an example 

https://user-images.githubusercontent.com/36929077/194013017-0699fc02-2734-454f-9e05-b5816916da11.mp4

**Comment by nimr77** [comment]
oh yes true the example freeze, sorry I will fix it now, since I'm using it on another project it's working there

**Comment by Jamalianpour** [comment]
I clone your fork and run, but it wasn't work for me.
What is your flutter version?

**Comment by nimr77** [comment]
ok I have fixed it now
it was an issue I made with the example, sorry my bad 

https://user-images.githubusercontent.com/36929077/194015165-582da4ec-dfa1-44ac-a5be-ea53139d66a1.mp4

**Comment by Jamalianpour** [comment]
Thank you,
Now when change page by scrolling sidemenu doesn't change


https://user-images.githubusercontent.com/29815018/194020100-cb75cadc-ae43-4652-9593-a7b105e2aa42.mp4

**Comment by nimr77** [comment]
hmm interesting 

try adding this on initstate, on the example 
```
    page.addListener(() {
      sideMenu.changePage(page.page!.toInt());
    });
```

**Pull request merged**
